### ISSUE TITLE
同时绑定图片和视频会报错

### ISSUE THREAD

**Issue by Greathfs** [xionger0520/flowcamera#17]
2020-06-01 13:15:14.515 19456-19456/com.hbzhou.open.camera E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hbzhou.open.camera, PID: 19456
    java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.impl.ImageCaptureConfig@7887eda, androidx.camera.core.impl.VideoCaptureConfig@11b41e8, androidx.camera.core.impl.PreviewConfig@27faea6]
        at androidx.camera.camera2.internal.Camera2DeviceSurfaceManager.getSuggestedResolutions(Camera2DeviceSurfaceManager.java:191)
        at androidx.camera.core.CameraX.calculateSuggestedResolutions(CameraX.java:949)
        at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:351)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:230)
        at androidx.camera.view.CameraXModule.bindToLifecycleAfterViewMeasured(CameraXModule.java:244)
        at androidx.camera.view.CameraXModule.bindToLifecycle(CameraXModule.java:157)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:134)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:126)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:344)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by Greathfs** [comment]
这个问题我自己在使用CameraX的时候页遇到过了 目前没想好怎么解决 作者有好的思路可以提供下吗

**Comment by Greathfs** [comment]
红米6s会出现这个问题我手里的另外一台华为就没有这个问题

**Comment by xionger0520** [comment]
@Greathfs 小米的设备让人头疼  哪个系统版本

**Comment by Greathfs** [comment]
红米6pro miui11 android10

**Comment by xionger0520** [comment]
@Greathfs 跑的是我的DEMO吗 还是依赖1.1.3测试的？

**Comment by Phyzait** [comment]
这边的小米也出现同样的问题了... 用的是CamreaX

**Comment by Greathfs** [comment]
> @Greathfs 跑的是我的DEMO吗 还是依赖1.1.3测试的？

跑的demo

**Comment by xionger0520** [comment]
@Greathfs 那你要么用CustomCameraView 要么等CameraX更新吧
