### ISSUE TITLE
这个库有待测试

### ISSUE THREAD

**Issue by zhangwenxiang26** [xionger0520/flowcamera#2]
红米   6.0    第一次点击进去有预览，退出，再次点按钮进去，直接黑屏
华硕  9.0    偶尔出现黑屏，长按录制  会闪屏  录制完成  播放也会闪屏；最终要的是会崩溃，
录屏完成底部的  返回  与  确定按钮   平移动画会异常  ，
我就拿了两个手机随便点点  不是崩溃，就是黑屏，问题好多的，
加油！！！！

把  bugly  集成下 收集下  bug  
加油！！！！

用java 写不好吗，kotlin  看不懂！
加油！！！！

看好你油
加油！！！！

**Comment by xionger0520** [comment]
@zhangwenxiang26 动态权限申请了吗 必须申请相机 麦克风 和存储权限  我测了也不少并没有出现问题 
这个是CameraX写的  兼容性应该比原生调用相机api好使  有问题 给个崩溃日志

**Comment by xionger0520** [comment]
@zhangwenxiang26 录制的视频和照片并不会闪频  只是调用的时候会闪一下 而已  不影响使用

**Comment by zhangwenxiang26** [comment]
用的就是当前  demo   权限都有
红米  6.0   首次进入录频页面正常，点击返回按钮  重新进入一直黑屏
三星  8.1   录制视频完成后，底部的 重置与确定按钮的平移动画会异常，然后播放视频的时候会黑屏
                 录屏页面一旦黑频，点就录制按钮必崩
录制与播放  有个黑影一闪而过

**Comment by zhangwenxiang26** [comment]
老铁，没骗你，真的

**Comment by xionger0520** [comment]
@zhangwenxiang26 重置和确定按钮的平移动画会异常指的是在这两个按钮平移动画的时候就崩溃了吗
你把崩溃日志贴出来我看看  那黑影就是拍摄和录制的过度动画就是时间长了一点  毕竟CameraX现在还在alpha版本  等正式版肯定会好很多   我会及时更新CameraX版本  感谢反馈

**Comment by zhangwenxiang26** [comment]
@xionger0520    重置和确定按钮的平移动画 比正常情况平移的慢  没崩  但直接黑屏
首先会这样
![94db9781860c5c0c16f2a65391af81a](https://user-images.githubusercontent.com/19923561/71404079-8cdf7680-266c-11ea-9887-b1684b24352c.jpg)

然后
![f5eccb735edecc8e5de1aeb916925ce](https://user-images.githubusercontent.com/19923561/71404123-aa144500-266c-11ea-9074-2fb4038a5af2.jpg)

**Comment by zhangwenxiang26** [comment]
能看到图片吗？   只要   app 不杀死  就如录屏页面一直黑屏，一旦点击录制就会崩溃
2019-12-24 16:46:07.029 2782-23201/? E/Exynos_OSAL_Android: [Exynos_OSAL_LockMetaData]: Failed to Exynos_OSAL_GetInfoFromMetaData (err:0x80001005)
2019-12-24 16:46:07.030 2782-23201/? E/EXYNOS_H264_ENC: [0xecfb1c00][Exynos_H264Enc_SrcIn] Failed to H264CodecSrcSetup(0xee0a6108)
2019-12-24 16:46:07.032 2782-23191/? E/Exynos_OSAL_Android: [Exynos_OSAL_UnlockMetaData]: Failed to Exynos_OSAL_GetInfoFromMetaData (err:0x80001005)
2019-12-24 16:46:07.036 22691-23182/com.hbzhou.open.CameraView E/MPEG4Writer: Stop() called but track is not started
2019-12-24 16:46:07.055 2782-17140/? E/OMXNodeInstance: getConfig(0xee618a20:Exynos.AVC.Encoder, ConfigLatency(0x6f800005)) ERROR: UnsupportedIndex(0x8000101a)
2019-12-24 16:46:07.055 2782-17140/? E/OMXNodeInstance: getConfig(0xee618a20:Exynos.AVC.Encoder, ConfigAndroidIntraRefresh(0x6f60000a)) ERROR: UnsupportedIndex(0x8000101a)
2019-12-24 16:46:07.069 2782-19900/? E/OMXNodeInstance: getConfig(0xee618ae0:google.aac.encoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Undefined(0x80001001)
2019-12-24 16:46:07.071 2654-2827/? E/echo_reference_processing: remove_echoReference_effect: error - reset preproc_list
2019-12-24 16:46:07.071 2763-2817/? E/AudioFlinger::EffectModule: Error when removing effect: -22
2019-12-24 16:46:07.072 2763-2817/? E/AudioFlinger::EffectModule: Error when removing effect: -38
2019-12-24 16:46:07.105 22691-22758/com.hbzhou.open.CameraView E/AndroidRuntime: FATAL EXCEPTION: CameraX-
    Process: com.hbzhou.open.CameraView, PID: 22691
    java.lang.IllegalStateException
        at androidx.core.util.Preconditions.checkState(Preconditions.java:96)
        at androidx.core.util.Preconditions.checkState(Preconditions.java:108)
        at androidx.camera.camera2.internal.Camera2CameraImpl.openCaptureSession(Camera2CameraImpl.java:927)
        at androidx.camera.camera2.internal.Camera2CameraImpl.onUseCaseReset(Camera2CameraImpl.java:648)
        at androidx.camera.camera2.internal.Camera2CameraImpl$12.run(Camera2CameraImpl.java:633)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2019-12-24 16:46:07.123 2776-3255/? E/MediaPlayerService: offset error
2019-12-24 16:46:07.124 22691-22691/com.hbzhou.open.CameraView E/MediaPlayerNative: Unable to create media player
2019-12-24 16:46:07.190 2776-3255/? E/MetadataRetrieverClient: offset (0) bigger than file size (0)

**Comment by xionger0520** [comment]
@zhangwenxiang26 那这种情况的时候  你点击确定看看相册有没有这个图片  能不能正常显示  
我没有你这个机型  不好复现

**Comment by zhangwenxiang26** [comment]
![image](https://user-images.githubusercontent.com/19923561/71404677-2bb8a280-266e-11ea-9ba8-cb801533c609.png)

**Comment by zhangwenxiang26** [comment]
上述情况，没有录制成功

**Comment by xionger0520** [comment]
@zhangwenxiang26 只是录视频会这样  还是拍照也会黑屏并且相册看不到拍摄的照片

**Comment by zhangwenxiang26** [comment]
三星     SM-A260G   8.1.0     拍照没问题

**Comment by xionger0520** [comment]
@zhangwenxiang26 意思是小米的拍照和录视频都有问题吗？ 录视频结束到预览之前黑屏  那录制的时候能正常预览吗？

**Comment by xionger0520** [comment]
@zhangwenxiang26 你这个问题已经定位了  是CameraX兼容性问题  只能等待更新了
毕竟不是正式版  google也搞不定国内大厂的深度优化 唉

**Comment by zhangwenxiang26** [comment]
@xionger0520    
红米 note 4      6.0    国产
使用当前 demo
首次点击按钮进入录制页面，预览正常，不做任何操作，返回上一页，
再次点击按钮进入录制页面，录制页面黑屏，之后进入录制页面一直黑屏

**Comment by xionger0520** [comment]
@zhangwenxiang26 别再说小米的机型了  我试了两个小米都有问题

**Comment by zhangwenxiang26** [comment]
。。。
加油，慢慢优化。慢慢来，没事的。

**Comment by xionger0520** [comment]
@zhangwenxiang26 拿google官方demo在小米手机上都崩溃   只能等更新了  醉了我

**Comment by xionger0520** [comment]
@zhangwenxiang26 老哥  点个star  CameraX一出新版本我会及时更新 感谢支持

**Comment by zhangwenxiang26** [comment]
点了

**Comment by xionger0520** [comment]
@zhangwenxiang26 有啥反馈可以加q  或者微信 也可以email

**Comment by xionger0520** [comment]
@zhangwenxiang26 升级到1.0.5 使用CustomCameraView试试  看看还是否有这些问题

**Comment by xionger0520** [comment]
@zhangwenxiang26 老哥  如果测试了反馈一下效果  感谢

**Comment by xionger0520** [comment]
@zhangwenxiang26 你用新版本再测测 看看你这问题还有么  兼容性好多了
