### ISSUE TITLE
在Redmi 6A MIUI 10.2上会出现闪退

### ISSUE THREAD

**Issue by 373518155** [xionger0520/flowcamera#23]
在Redmi 6A MIUI 10.2上会出现闪退，异常栈如下

2020-06-15 12:05:54.287 8287-8287/com.hbzhou.open.camera E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hbzhou.open.camera, PID: 8287
    java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.impl.PreviewConfig@56708a7, androidx.camera.core.impl.VideoCaptureConfig@30521c1, androidx.camera.core.impl.ImageCaptureConfig@19c8acb]
        at androidx.camera.camera2.internal.Camera2DeviceSurfaceManager.getSuggestedResolutions(Camera2DeviceSurfaceManager.java:191)
        at androidx.camera.core.CameraX.calculateSuggestedResolutions(CameraX.java:949)
        at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:351)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:230)
        at androidx.camera.view.CameraXModule.bindToLifecycleAfterViewMeasured(CameraXModule.java:244)
        at androidx.camera.view.CameraXModule.bindToLifecycle(CameraXModule.java:157)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:134)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:126)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:344)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by xionger0520** [comment]
@373518155 CameraX的问题等更新吧

**Comment by yymjr** [comment]
same problem!!!!

**Comment by zhoushuangli** [comment]
很多手机都是这个问题
