### ISSUE TITLE
在小米6 8.0问题也是闪退,测了很多手机,一半在闪退,华为手机Android 10是好的

### ISSUE THREAD

**Issue by zhoushuangli** [xionger0520/flowcamera#33]
Process: com.hbzhou.open.camera, PID: 21958
    java.lang.IllegalArgumentException: No supported surface combination is found for camera device - Id : 0.  May be attempting to bind too many use cases. Existing surfaces: [] New configs: [androidx.camera.core.impl.PreviewConfig@d5f2dad, androidx.camera.core.impl.ImageCaptureConfig@4c24b71, androidx.camera.core.impl.VideoCaptureConfig@87101d7]
        at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:266)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:424)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:275)
        at androidx.camera.view.CameraXModule.bindToLifecycleAfterViewMeasured(CameraXModule.java:244)
        at androidx.camera.view.CameraXModule.bindToLifecycle(CameraXModule.java:154)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:132)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:124)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:344)
        at android.os.Handler.handleCallback(Handler.java:793)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:249)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by xionger0520** [comment]
@zhoushuangli 用的哪个版本  这个问题两种可能 1.库不兼容 2.小米改动系统代码没有兼容原生系统

**Comment by zhoushuangli** [comment]
我发现不是小米一款手机的问题,在6.0全部奔溃,我现在直接从你的demo上跑的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hbzhou"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 上午9:59
收件人: "xionger0520/flowcamera"<flowcamera@noreply.github.com&gt;; 
抄送: "蛋蛋"<554707615@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xionger0520/flowcamera] 在小米6 8.0问题也是闪退,测了很多手机,一半在闪退,华为手机Android 10是好的 (#33)





 
@zhoushuangli 用的哪个版本  这个问题两种可能 1.库不兼容 2.小米改动系统代码没有兼容原生系统

**Comment by xionger0520** [comment]
@zhoushuangli 试试我刚更新的 demo 不行的话只有等更新了

**Comment by zhoushuangli** [comment]
好,我试下,你说等更新是等google更新吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hbzhou"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 上午10:12
收件人: "xionger0520/flowcamera"<flowcamera@noreply.github.com&gt;; 
抄送: "蛋蛋"<554707615@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xionger0520/flowcamera] 在小米6 8.0问题也是闪退,测了很多手机,一半在闪退,华为手机Android 10是好的 (#33)





 
@zhoushuangli 试试我刚更新的 demo 不行的话只有等更新了

**Comment by zhoushuangli** [comment]
还是闪退




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "hbzhou"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 上午10:12
收件人: "xionger0520/flowcamera"<flowcamera@noreply.github.com&gt;; 
抄送: "蛋蛋"<554707615@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xionger0520/flowcamera] 在小米6 8.0问题也是闪退,测了很多手机,一半在闪退,华为手机Android 10是好的 (#33)





 
@zhoushuangli 试试我刚更新的 demo 不行的话只有等更新了

**Comment by Mr-jinPH** [comment]
我使用华硕测试机也是这个bug,华为手机就没事
