### ISSUE TITLE
华为8x max闪退

### ISSUE THREAD

**Issue by czl0325** [xionger0520/flowcamera#35]
2020-10-09 15:24:30.848 6545-6545/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tongye.carpos.beta, PID: 6545
    java.lang.NoSuchFieldError: No field DEFAULT_ASPECT_RATIO_PORTRAIT of type Landroid/util/Rational; in class Landroidx/camera/core/impl/ImageOutputConfig; or its superclasses (declaration of 'androidx.camera.core.impl.ImageOutputConfig' appears in /data/app/com.tongye.carpos.beta-Wlsj3nHMU2o5dOsoiUXWWA==/base.apk)
        at androidx.camera.camera2.internal.ImageCaptureConfigProvider.getConfig(ImageCaptureConfigProvider.java:75)
        at androidx.camera.camera2.internal.ImageCaptureConfigProvider.getConfig(ImageCaptureConfigProvider.java:38)
        at androidx.camera.core.impl.ExtendableUseCaseConfigFactory.getConfig(ExtendableUseCaseConfigFactory.java:47)
        at androidx.camera.core.CameraX.getDefaultUseCaseConfig(CameraX.java:178)
        at androidx.camera.core.ImageCapture.getDefaultBuilder(ImageCapture.java:409)
        at androidx.camera.core.internal.CameraUseCaseAdapter.calculateSuggestedResolutions(CameraUseCaseAdapter.java:294)
        at androidx.camera.core.internal.CameraUseCaseAdapter.addUseCases(CameraUseCaseAdapter.java:176)
        at androidx.camera.lifecycle.LifecycleCamera.bind(LifecycleCamera.java:181)
        at androidx.camera.lifecycle.LifecycleCameraRepository.bindToLifecycleCamera(LifecycleCameraRepository.java:276)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:424)
        at androidx.camera.lifecycle.ProcessCameraProvider.bindToLifecycle(ProcessCameraProvider.java:275)
        at androidx.camera.view.CameraXModule.bindToLifecycleAfterViewMeasured(CameraXModule.java:243)
        at androidx.camera.view.CameraXModule.bindToLifecycle(CameraXModule.java:153)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:131)
        at androidx.camera.view.CameraXModule$2.onSuccess(CameraXModule.java:123)
        at androidx.camera.core.impl.utils.futures.Futures$CallbackListener.run(Futures.java:344)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by GirlFriendNotFind** [comment]
红米k30 pro也一样

**Comment by czl0325** [comment]
作者测试都不测试就直接丢上来，搞不明白怎么当开发的

**Comment by xionger0520** [comment]
> 作者测试都不测试就直接丢上来，搞不明白怎么当开发的

我辛辛苦苦写个库给大家用就是为了被你喷？？？

**Comment by czl0325** [comment]
写的库至少测试下再放上来，那我写个helloworld放上来你喷我不。

**Comment by xionger0520** [comment]
@czl0325 至少测试一下再放上来？所以你以为我没测？？？每年多少机型多少系统版本？？？我要怎么一一去测？？
明明你那报错信息就是camerax框架里面报出来你自己仔细看了吗？就来喷？？？google不更新我拿脚给你解决？？做个有素质的人好吗？？？

**Comment by nxnyk** [comment]
> @czl0325 至少测试一下再放上来？所以你以为我没测？？？每年多少机型多少系统版本？？？我要怎么一一去测？？
> 明明你那报错信息就是camerax框架里面报出来你自己仔细看了吗？就来喷？？？google不更新我拿脚给你解决？？做个有素质的人好吗？？？

顶一波作者，嗟来之食，还BB赖赖，不是说怎么协助一起解决问题，就光会喷的nt，就是这么当人的？？？

**Comment by xiongkai888** [comment]
顶楼主！楼主bug处理好了没？刚好项目需要用到这个东东，  demo里的apk安装倒是能用，小米6 demo运行点击就闪退

**Comment by xiaoxing1992** [comment]
顶楼主！

**Comment by 1006245347** [comment]
支持楼主！

**Comment by vastsea88** [comment]
> 写的库至少测试下再放上来，那我写个helloworld放上来你喷我不。

这也能喷，有能耐自己上一个！
