### ISSUE TITLE
 使用CustomCameraView报错

### ISSUE THREAD

**Issue by solochen** [xionger0520/flowcamera#39]
使用CustomCameraView 打开直接报错，报错信息如下：

2020-12-16 18:58:29.663 10637-10774/com.hbzhou.open.camera E/AndroidRuntime: FATAL EXCEPTION: GLThread 598
    Process: com.hbzhou.open.camera, PID: 10637
    java.lang.NoSuchMethodError: No static method get-impl([II)I in class Lkotlin/UIntArray; or its super classes (declaration of 'kotlin.UIntArray' appears in /data/app/com.hbzhou.open.camera-87KBRtiwAEzaKaP-kgaEoA==/base.apk)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:90)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:23)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:22)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(Unknown Source:6)
        at com.otaliastudios.cameraview.internal.GlTextureDrawer.<init>(GlTextureDrawer.java:35)
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onSurfaceCreated(GlCameraPreview.java:148)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)
2020-12-16 18:58:29.663 10637-10774/com.hbzhou.open.camera E/AndroidRuntime: FATAL EXCEPTION: GLThread 598
    Process: com.hbzhou.open.camera, PID: 10637
    java.lang.NoSuchMethodError: No static method get-impl([II)I in class Lkotlin/UIntArray; or its super classes (declaration of 'kotlin.UIntArray' appears in /data/app/com.hbzhou.open.camera-87KBRtiwAEzaKaP-kgaEoA==/base.apk)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:90)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:23)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(GlTexture.kt:22)
        at com.otaliastudios.opengl.texture.GlTexture.<init>(Unknown Source:6)
        at com.otaliastudios.cameraview.internal.GlTextureDrawer.<init>(GlTextureDrawer.java:35)
        at com.otaliastudios.cameraview.preview.GlCameraPreview$Renderer.onSurfaceCreated(GlCameraPreview.java:148)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1293)

**Comment by solochen** [comment]
cameraview2.6.3 降级到2.6.2 可以了
api 'com.otaliastudios:cameraview:2.6.2'


https://github.com/natario1/CameraView/issues/940
