### ISSUE TITLE
华为android 10使用FlowCameraView闪退

### ISSUE THREAD

**Issue by MYaoDan** [xionger0520/flowcamera#41]
### 华为android10使用FlowCameraView闪退，使用CustomCameraView没有闪退
`
2021-05-12 17:27:26.381 3309-4760/com.gwm.sharing.platform E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@d39d30d
2021-05-12 17:27:26.471 3309-4784/com.gwm.sharing.platform E/AndroidRuntime: FATAL EXCEPTION: CameraX-core_camera_0
    Process: com.gwm.sharing.platform, PID: 3309
    java.lang.AbstractMethodError: abstract method "androidx.camera.core.impl.CameraFactory androidx.camera.core.impl.CameraFactory$Provider.newInstance(android.content.Context, androidx.camera.core.impl.CameraThreadConfig, androidx.camera.core.CameraSelector)"
        at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$9$CameraX(CameraX.java:569)
        at androidx.camera.core.-$$Lambda$CameraX$u-Xx2b6YXY5GXNXRh-mDiDnHdpQ.run(Unknown Source:10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
2021-05-12 17:27:26.477 3880-7462/? E/AwareLog: SPKEQSchedFeature: Uid has been sent, ignore.
`
还有一个问题，录像的时候一开始会闪一下，能解决吗？

**Comment by techtickcn** [comment]
同样问题 三星n9500也会卡一会，而且卡住部分录不上

**Comment by zjianflys** [comment]
我的华为android 好像没得问题咯 但是启动的时候有黑屏一会
