### ISSUE TITLE
小米 mi8 miui12.0.4 打开后，不拍，退出当前界面，息屏 亮屏就会崩溃：java.lang.IllegalStateException: view.display must not be null

### ISSUE THREAD

**Issue by AreYReady** [xionger0520/flowcamera#42]
2021-05-13 15:24:39.222 24812-24812/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fjthpay.chat, PID: 24812
    java.lang.IllegalStateException: view.display must not be null
        at com.hbzhou.open.flowcamera.FlowCameraView2$displayListener$1.onDisplayChanged(FlowCameraView2.kt:623)
        at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:699)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by AreYReady** [comment]
测试发现，我是用了FlowCameraView2这个控件出现的这个问题，其他控件没有
