### ISSUE TITLE
折叠屏闪退

### ISSUE THREAD

**Issue by longkehuawei** [xionger0520/flowcamera#45]
10-17 10:13:01.936 1094-1307/? E Parcel  : Reading a NULL string not supported here.
10-17 10:13:01.936 1094-1307/? E HiEvent : java.lang.IllegalStateException: Call triggerSingleCapture after configured the camera
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at ohos.media.camera.device.impl.CameraImpl.triggerSingleCapture(CameraImpl.java:532)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.CameraInterface.takePicture(CameraInterface.java:572)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.state.PreviewState.capture(PreviewState.java:46)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.state.CameraMachine.capture(CameraMachine.java:115)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.JCameraView$2.takePictures(JCameraView.java:302)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.CaptureLayout$2.takePictures(CaptureLayout.java:303)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.CaptureButton$1.onEnd(CaptureButton.java:247)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.util.ValueAnimator.setState(ValueAnimator.java:150)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.util.ValueAnimator.access$100(ValueAnimator.java:12)
10-17 10:13:01.936 1094-1307/? E HiEvent : 	at com.samoyed.credit.hmsevice.flowcamera.util.ValueAnimator$1.onEnd(ValueAnimator.jav
10-17 10:13:01.938 789-789/? E TS_HAL  : huawei_tp_run_command: call

**Comment by xionger0520** [comment]
@longkehuawei 你这个错误日志 为啥包名都不是我的库的  自己下载下去改代码了？
