### ISSUE TITLE
三星 S50S手机预览的画面像马赛克一样, 但是长按录制和拍照出来后是正常的 

### ISSUE THREAD

**Issue by wahyip** [xionger0520/flowcamera#6]

**Comment by xionger0520** [comment]
你这样描述我也不能判断啥问题啊   是不是权限的问题 或者有没有啥错误日志？？

**Comment by xionger0520** [comment]
@wahyip 目前还有这个问题？

**Comment by ailiboy520** [comment]
应该是custom引用的第三方camerview没有指定相应的属性导致的

        <com.otaliastudios.cameraview.CameraView
            android:id="@+id/video_preview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:cameraExperimental="true"
            app:cameraEngine="camera2"
            app:cameraPreview="glSurface"
            app:cameraPlaySounds="true"
            app:cameraGrid="off"
            app:cameraFlash="auto"
            app:cameraAudio="on"
            app:cameraFacing="back"
            app:cameraGestureTap="autoFocus"
            app:cameraGestureLongTap="none"
            app:cameraGesturePinch="zoom"
            app:cameraGestureScrollHorizontal="filterControl1"
            app:cameraGestureScrollVertical="exposureCorrection"
            app:cameraMode="picture"/>

**Comment by xionger0520** [comment]
@ailiboy520 意思是你加了某个属性就没有这问题了？

**Comment by wahyip** [comment]
> 你这样描述我也不能判断啥问题啊 是不是权限的问题 或者有没有啥错误日志？？

一直存在这个问题, 初步找到是相机计算问题, CameraInterface类以下代码:
  mParams = mCamera.getParameters();
                Camera.Size previewSize = CameraParamUtil.getInstance().getPreviewSize(mParams
                        .getSupportedPreviewSizes(), 1000, screenProp);
                Camera.Size pictureSize = CameraParamUtil.getInstance().getPictureSize(mParams
                        .getSupportedPictureSizes(), 1200, screenProp);
 mParams.setPreviewSize(previewSize.width, previewSize.height);

还有就是在华为畅享9PLUS, 长按录制, 松开手指还是会接着录制~ 并且反复长按点击按钮会出现以下报错:
 java.lang.RuntimeException: getParameters failed (empty parameters)
at android.hardware.Camera.native_getParameters(Native Method)
at android.hardware.Camera.getParameters(Camera.java:1910)
at com.cjt2325.cameralibrary.CameraInterface.doStartPreview(CameraInterface.java:369)
at com.cjt2325.cameralibrary.state.BorrowVideoState.start(BorrowVideoState.java:28)
at com.cjt2325.cameralibrary.state.CameraMachine.start(CameraMachine.java:71)
at com.cjt2325.cameralibrary.JCameraView.resetState(JCameraView.java:438)
at com.cjt2325.cameralibrary.state.BorrowVideoState.cancle(BorrowVideoState.java:70)
at com.cjt2325.cameralibrary.state.CameraMachine.cancle(CameraMachine.java:111)
at com.cjt2325.cameralibrary.JCameraView$4.cancel(JCameraView.java:241)
at com.cjt2325.cameralibrary.CaptureLayout$3.onClick(CaptureLayout.java:261)
at android.view.View.performClick(View.java:6897)
at android.widget.TextView.performClick(TextView.java:12693)
at android.view.View$PerformClick.run(View.java:26101)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by xionger0520** [comment]
@wahyip 加微 我看看你代码

**Comment by xionger0520** [comment]
@wahyip 你这个报错路径很明显还是那个JCameraView 确定用的是我的库？？？
